FROM ubuntu:18.04

# dpkg-dev: for dpkg-scanpackages
# software-properties-common: for add-apt-repository
RUN apt-get -y update && apt-get -y install build-essential dpkg-dev software-properties-common wget

# for boost 1.67
RUN add-apt-repository ppa:mhier/libboost-latest

# setup apt repository
RUN mkdir -p /gt/apt-repo
COPY libgtirb.deb /gt/apt-repo
RUN cd /gt/apt-repo && dpkg-scanpackages . /dev/null > Packages
RUN echo "\ndeb [trusted=yes] file:/gt/apt-repo ./\n" >> /etc/apt/sources.list

# test the installer
RUN apt-get update && apt-get install -y --allow-unauthenticated libgtirb
