FROM ubuntu:16.04 AS test-base
# dpkg-dev: for dpkg-scanpackages
# software-properties-common: for add-apt-repository
RUN apt-get -y update && apt-get -y install build-essential dpkg-dev software-properties-common wget
RUN add-apt-repository ppa:maarten-fonville/protobuf
RUN add-apt-repository ppa:mhier/libboost-latest
RUN mkdir -p /gt/apt-repo
COPY libgtirb.deb /gt/apt-repo
COPY libgtirb-dev.deb /gt/apt-repo
RUN cd /gt/apt-repo && dpkg-scanpackages . /dev/null > Packages
RUN echo "\ndeb file:/gt/apt-repo ./\n" >> /etc/apt/sources.list

FROM test-base AS test-libgtirb-dev
RUN add-apt-repository ppa:jonathonf/gcc-7.1
RUN apt-get update && apt-get install -y gcc-7 g++-7
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
WORKDIR /test/
COPY .ci/test-install.cpp test-install.cpp
RUN apt-get update && apt-get install -y --allow-unauthenticated libgtirb-dev
RUN g++-7 test-install.cpp -std=c++17 -o test-install -lgtirb -lstdc++
RUN ./test-install

FROM test-base AS test-libgtirb
RUN apt-get update && apt-get install -y --allow-unauthenticated libgtirb
COPY --from=test-libgtirb-dev /test/test-install /test/test-install
WORKDIR /test/
RUN ./test-install
