FROM ubuntu:16.04

# dpkg-dev: for dpkg-scanpackages
# software-properties-common: for add-apt-repository
RUN apt-get -y update && apt-get -y install build-essential dpkg-dev software-properties-common wget

# gcc-7 is used by the test
RUN add-apt-repository ppa:jonathonf/gcc-7.1
RUN apt-get update && apt-get install -y gcc-7 g++-7

# for protobuf >=3.0.0
RUN add-apt-repository ppa:maarten-fonville/protobuf

# for boost 1.67
RUN add-apt-repository ppa:mhier/libboost-latest

# setup apt repository
RUN mkdir -p /gt/apt-repo
COPY GTIRB-*-Linux.deb /gt/apt-repo
RUN cd /gt/apt-repo && dpkg-scanpackages . /dev/null > Packages
RUN echo "\ndeb file:/gt/apt-repo ./\n" >> /etc/apt/sources.list

# test the installer
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
COPY .ci/test-install.cpp test-install.cpp
RUN apt-get update && apt-get install -y --allow-unauthenticated gtirb
ARG CXX_COMPILER=c++
RUN $CXX_COMPILER test-install.cpp -std=c++17 -o test-install -lgtirb -lstdc++
