FROM ubuntu:18.04

# dpkg-dev: for dpkg-scanpackages
# software-properties-common: for add-apt-repository
RUN apt-get -y update && apt-get -y install build-essential dpkg-dev software-properties-common wget

RUN add-apt-repository ppa:mhier/libboost-latest

# setup apt repository
RUN mkdir -p /gt/apt-repo
COPY python3-gtirb.deb /gt/apt-repo
RUN cd /gt/apt-repo && dpkg-scanpackages . /dev/null > Packages
RUN echo "\ndeb [trusted=yes] file:/gt/apt-repo ./\n" >> /etc/apt/sources.list

# test the installer
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
COPY .ci/test-install.py test-install.py
RUN apt-get update && apt-get install -y --allow-unauthenticated python3-gtirb
RUN python3 test-install.py
