ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG CXX_COMPILER=g++-7

# Install capstone
WORKDIR /gt/
RUN apt-get -y install libcapstone-dev

# Build GTIRB
WORKDIR /gt/gtirb/build
ARG BUILD_TYPE=RelWithDebInfo
RUN cmake ../ -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCMAKE_BUILD_TYPE=$BUILD_TYPE -B.
RUN make -j

RUN TestGTIRB
