FROM ubuntu:16.04
SHELL ["/bin/bash", "-c"]

RUN apt-get -y update && apt-get -y install software-properties-common

# for protobuf (only required on ubuntu 16)
RUN add-apt-repository ppa:maarten-fonville/protobuf

# for boost
RUN add-apt-repository ppa:mhier/libboost-latest

# for our projects
ARG REPO_ROOT=""
RUN echo "deb $REPO_ROOT/xenial ./" >> /etc/apt/sources.list

RUN apt-get -y update

ARG PROJECT="$PROJECT"
RUN apt-get -y --allow-unauthenticated install $PROJECT
RUN find / -iname *$PROJECT.so -exec ldd \{\} \;
