FROM ubuntu:18.04 AS test-base
# dpkg-dev: for dpkg-scanpackages
# software-properties-common: for add-apt-repository
RUN apt-get -y update && apt-get -y install build-essential dpkg-dev software-properties-common wget
RUN add-apt-repository ppa:mhier/libboost-latest
RUN mkdir -p /gt/apt-repo
COPY libgtirb-dev.deb /gt/apt-repo
COPY libgtirb.deb /gt/apt-repo
COPY python3-gtirb.deb /gt/apt-repo
RUN cd /gt/apt-repo && dpkg-scanpackages . /dev/null > Packages
RUN echo "\ndeb [trusted=yes] file:/gt/apt-repo ./\n" >> /etc/apt/sources.list

FROM test-base as test-libgtirb-dev
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
COPY .ci/test-install.cpp test-install.cpp
RUN apt-get update && apt-get install -y --allow-unauthenticated libgtirb-dev
RUN g++ test-install.cpp -std=c++17 -o test-install -lgtirb -lstdc++
RUN ./test-install

FROM test-base AS test-libgtirb
RUN apt-get update && apt-get install -y --allow-unauthenticated libgtirb
COPY --from=test-libgtirb-dev /test-install /test-install
WORKDIR /test-install
RUN ./test-install

FROM test-base as test-python3-gtirb
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
COPY .ci/test-install.py test-install.py
RUN apt-get update && apt-get install -y --allow-unauthenticated python3-gtirb
RUN python3 test-install.py
