ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG CXX_COMPILER=g++

# Install capstone
WORKDIR /gt/
RUN pacman --noconfirm -Syu capstone

# Build GTIRB
WORKDIR /gt/gtirb/build
RUN cmake ../ -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -B.
RUN make -j

RUN TestGTIRB
