ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG CXX_COMPILER=g++-7

# Install capstone
WORKDIR /gt/
COPY ./libcapstone-dev_4.0.1-1_amd64.deb ./
RUN dpkg -i libcapstone-dev_4.0.1-1_amd64.deb

# Build GTIRB
WORKDIR /gt/gtirb/build
RUN cmake ../ -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -B.
RUN make -j

RUN TestGTIRB
