# This file runs a test to ensure that this library can be installed once built,
# and C++ code is able to link to it with the proper `-l` flags only.
#
# This test should be distro-agnostic.

ARG CXX_COMPILER=g++-7
ARG PROTOBUF_PYTHON_RUNTIME=cpp

ARG IMAGE=docker.grammatech.com/rewriting/gtirb/ubuntu18-gcc7
FROM $IMAGE as base

# After saying that this should be distro-agnostic, we need to ensure that venv
# is installed correctly. So far this seems to only be an issue for our Ubuntu
# builds, so if we're on Ubuntu, install venv.

RUN if [ "X`lsb_release -is`" = "XUbuntu" ] ; then \
        apt-get update && apt-get -y install python3-venv ; \
    fi

COPY .ci/test-install* /gt/gtirb/.ci/

WORKDIR /

ARG CXX_COMPILER
ENV CXX=$CXX_COMPILER
ARG PROTOBUF_PYTHON_RUNTIME
ENV PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=$PROTOBUF_PYTHON_RUNTIME

########
# Test default installation to /usr/local

FROM base

RUN make -C /gt/gtirb/build install && rm -rf /gt/gtirb/build
RUN /gt/gtirb/.ci/test-install-all.sh

########
# Test installing to a different prefix

FROM base

RUN cd /gt/gtirb/build && cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/prefix
RUN echo /tmp/prefix/lib/python$(python3 -c "import sys; print('%s.%s' % sys.version_info[:2])")/site-packages > pydir
RUN mkdir -p $(cat pydir)
RUN PYTHONPATH=$(cat pydir) \
    make -C /gt/gtirb/build install && rm -rf /gt/gtirb/build
RUN PYTHONPATH=$(cat pydir) \
    CPPFLAGS=-I/tmp/prefix/include \
    LDFLAGS=-L/tmp/prefix/lib \
    LD_LIBRARY_PATH=/tmp/prefix/lib \
    /gt/gtirb/.ci/test-install-all.sh

########
# Test installing with DESTDIR

FROM base as destdir-install

RUN DESTDIR=/tmp/destdir make -C /gt/gtirb/build install

# Copy the DESTDIR onto a fresh base. This simulates DESTDIR packages and
# chroot

FROM base

COPY --from=destdir-install /tmp/destdir /
RUN rm -rf /gt/gtirb/build
RUN /gt/gtirb/.ci/test-install-all.sh

########
# Test installing python into a virtualenv

FROM base

RUN mkdir /tmp/myvenv && \
    python3 -m venv /tmp/myvenv && \
    sh -c '. /tmp/myvenv/bin/activate ; cd /gt/gtirb/build/python && python3 setup.py install' && \
    rm -rf /gt/gtirb/build
RUN sh -c '. /tmp/myvenv/bin/activate ; python3 /gt/gtirb/.ci/test-install.py'
