FROM ubuntu:18.04

RUN apt-get update \
    && apt-get -y install \
    python2.7 \
    python3 \
    python3-pip \
    clang-format \
    git \
    curl

RUN pip3 install pre-commit

COPY . /gt/gtirb/
WORKDIR /gt/gtirb/

RUN pre-commit autoupdate
RUN pre-commit run --all-files
