FROM archlinux/base

ARG CXX_COMPILER=g++
ARG EXTRA_CMAKE_FLAGS=

RUN pacman --noconfirm -Syu archlinux-keyring
RUN pacman --noconfirm -Syu base-devel boost protobuf git cmake python doxygen graphviz
COPY gtirb-git*.pkg.tar.xz /tmp/

# test the installer
ENV LD_LIBRARY_PATH /usr/local/lib:$LD_LIBRARY_PATH
COPY .ci/test-install.cpp test-install.cpp
RUN pacman --noconfirm -U /tmp/gtirb-git-*.pkg.tar.xz
RUN g++ test-install.cpp -std=c++17 -o test-install -lgtirb -lstdc++
