ARG BASE_IMAGE
FROM ${BASE_IMAGE}

ARG CXX_COMPILER=g++-7

# Install capstone
WORKDIR /gt/
RUN apt-get -y install libcapstone-dev

# Build GTIRB
WORKDIR /gt/gtirb/build
RUN cmake ../ -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -B.
RUN make -j

RUN TestGTIRB
