variables:
  LOCAL_IMAGE_NAME: '$CI_COMMIT_REF_SLUG-$CI_PIPELINE_ID'
  GIT_SUBMODULE_STRATEGY: recursive
  EXTRA_INDEX_URL: https://__token__:$GL_PKG_API_TOKEN@git.grammatech.com/api/v4/projects/1587/packages/pypi/simple
  # The follow two variables are used by the package-uploader.
  PROJECT_ID: $CI_PROJECT_ID
  PIPELINE_ID: $CI_PIPELINE_ID
  CONAN_PASSWORD: $CI_JOB_TOKEN

stages:
  - check-format
  - build
  - build-installers
  - test-setup
  - test-packages1
  - test-packages2
  - deploy
  - deploy-apt
  - upload

default:
  tags: [cluster]

check-format:
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  stage: check-format
  script:
    - |+
      pre-commit run --all-files --show-diff-on-failure || ( (cat <<EOF
      ================================================================================
      If this stage fails, the formatting of your changes may be incorrect.
      To automatically format your files, install pre-commit:
          pip3 install pre-commit
          pre-commit install
      pre-commit will now automatically format any files before commit.
      To fix any misformatted files, run:
          pre-commit run --all-files
      And then commit any changes.
      More information regarding pre-commit can be found at https://pre-commit.com.

      NOTE FOR PROJECTS WITH C/C++ CODE:
      pre-commit will by default use the correct version of every formatting tool
      EXCEPT FOR clang-format. You need to ensure the version of clang-format you
      use is EXACTLY version 6.0.0. This is available in Ubuntu 18 by default.

      See also:
          https://git.grammatech.com/research/meta/-/wikis/infrastructure/infrastructure#running-ci-jobs-locally-for-debugging
          http://otsego.grammatech.com/u4/Videos/2020-09-11-Lunchtime-Seminar/
      ================================================================================
      EOF
      ) && exit 1)

build-docs:
  stage: build
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - html
  script:
    - mkdir build
    - cd build
    # Need to configure Python API to get setup.py file
    - cmake .. -DGTIRB_ENABLE_TESTS=OFF
    # Install python dependencies
    - cd python
    - pip install -e '.[doc]'
    - cd ..
    # Re-configure to pick up python dependencies
    - cmake ..
    - make doc
    - mv doc/html ..

.build-template: &build
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - build
  script:
    - mkdir build
    - cd build
    - RELEASE_VERSION=OFF
    - '[[ ! $CI_COMMIT_REF_NAME =~ ^release-.* ]] || RELEASE_VERSION=ON'
    - cmake ../ -DCMAKE_CXX_COMPILER=${CXX_COMPILER} -DCPACK_DEBIAN_PACKAGE_RELEASE="$(lsb_release -sc)" -DCMAKE_BUILD_TYPE=$BUILD_TYPE -DGTIRB_STRIP_DEBUG_SYMBOLS=On -DGTIRB_RELEASE_VERSION=$RELEASE_VERSION
    - make -j
    - pip3 install -e python
    - ctest -V

build-ubuntu20-gcc:
  stage: build
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  variables:
    OS: 'ubuntu20'
    CXX_COMPILER: 'g++'
    CPACK_GENERATOR: 'DEB'
    BUILD_TYPE: 'RelWithDebInfo'
  <<: *build

build-ubuntu20-gcc-debug:
  stage: build
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  variables:
    OS: 'ubuntu20'
    CXX_COMPILER: 'g++'
    BUILD_TYPE: 'Debug'
  <<: *build

build-ubuntu20-clang-debug:
  stage: build
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  variables:
    OS: 'ubuntu20'
    CXX_COMPILER: 'clang++'
    BUILD_TYPE: 'Debug'
  <<: *build

build-static:
  stage: build
  image: $DOCKER_REGISTRY/rewriting/gtirb/static
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - build
  script:
    - mkdir build
    - cd build
    - cmake ../ -DGTIRB_BUILD_SHARED_LIBS=OFF -DGTIRB_PY_API=OFF
    - make -j
    - ctest -V
    # ensure that we produced a .a file instead of a .so
    - '[ -e lib/libgtirb.a ]'
    - '[ ! -e lib/libgtirb.so ]'

test-capstone-example:
  stage: test-packages1
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  needs: ['build-ubuntu20-gcc']
  script:
    - cd build
    - '[[ ! -f bin/ex-jumps ]]'
    - rm -rf *
    - apt-get install -y libcapstone-dev
    - cmake ..
    - make -j
    - '[[ -f bin/ex-jumps ]]'

coverage:
  stage: build
  needs: [check-format]
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  script:
    - mkdir build
    - cd build
    - pip install gcovr coverage
    - cmake -DENABLE_CODE_COVERAGE=ON ..
    - cmake --build .
    - pip3 install -e python
    - ctest
    - gcovr --exclude=googletest-src --exclude=doc --exclude=..*/proto --exclude=..*/test --root ..
    - cd python
    - coverage report --omit=gtirb/proto/* --show-missing

test-default-install:
  stage: test-packages1
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  variables:
    OS: 'ubuntu20'
    COMPILER: 'g++-9'
    PROTOBUF_PYTHON_RUNTIME: 'cpp'
  needs: ['build-ubuntu20-gcc']
  script:
    - cmake --build build
    - make -C build install && rm -rf build
    - LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH .ci/test-install-all.sh

test-default-install-static:
  stage: test-packages1
  image: $DOCKER_REGISTRY/rewriting/gtirb/static
  needs: ['build-static']
  script:
    - cmake --build build
    - make -C build install && rm -rf build
    - LD_LIBRARY_PATH=/usr/local/lib:$LD_LIBRARY_PATH .ci/test-install-static.sh

test-install-different-prefix:
  stage: test-packages1
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  variables:
    OS: 'ubuntu20'
    COMPILER: 'g++-9'
    PROTOBUF_PYTHON_RUNTIME: 'cpp'
  needs: ['build-ubuntu20-gcc']
  script:
    - cmake --build build
    - cd build && cmake .. -DCMAKE_INSTALL_PREFIX=/tmp/prefix
    - cd ..
    - make -C build install && rm -rf build
    - CPPFLAGS=-I/tmp/prefix/include LDFLAGS=-L/tmp/prefix/lib LD_LIBRARY_PATH=/tmp/prefix/lib .ci/test-install-all.sh

test-install-with-destdir:
  stage: test-packages1
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  variables:
    OS: 'ubuntu20'
    COMPILER: 'g++-9'
    PROTOBUF_PYTHON_RUNTIME: 'cpp'
  needs: ['build-ubuntu20-gcc']
  script:
    - cmake --build build
    - DESTDIR=/tmp/destdir make -C ./build install

test-install-python-virtualenv:
  stage: test-packages1
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  variables:
    OS: 'ubuntu20'
    COMPILER: 'g++-9'
    PROTOBUF_PYTHON_RUNTIME: 'cpp'
  needs: ['build-ubuntu20-gcc']
  script:
    - mkdir /tmp/myvenv
    - python3 -m venv /tmp/myvenv
    - sh -c '. /tmp/myvenv/bin/activate ; cd build/python && pip3 install .'
    - rm -rf build
    - sh -c '. /tmp/myvenv/bin/activate ; python3 .ci/test-install.py'

test-interop:
  stage: test-packages1
  needs: ['build-ubuntu20-gcc']
  image: ${DOCKER_REGISTRY}/rewriting/gtirb/ubuntu20
  script:
    - sh -c 'cd build/python && pip3 install .'
    - sh -c '.ci/test-interop.sh'

conan-linux-gcc9:
  stage: deploy
  needs: [check-format]
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  script:
    - python3 -m pip install --upgrade conan
    - conan profile new default --detect
    - conan profile update settings.compiler.libcxx=libstdc++11 default
    - conan remote add gitlab ${CI_API_V4_URL}/packages/conan
    - conan user ci_user -r gitlab -p
    - export PYTHONPATH="$(pwd)"
    - python3 .ci/build.py

.conan-windows: &conan-windows
  stage: deploy
  needs: [check-format]
  tags: [ddisasm-windows]
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - gtirb*.zip
  script:
    # Setting CI_PROJECT_DIR to $(pwd) because CI doesn't properly set CI_PROJECT_DIR with VirtualBox runners.
    - export CI_PROJECT_DIR=`cygpath -w $(pwd)`
    # Initialize
    - systeminfo
    - python -m pip install --upgrade conan
    - export PYTHONPATH=$CI_PROJECT_DIR
    # Setup Remote and Authenticate
    - conan remote add gitlab ${CI_API_V4_URL}/packages/conan
    - conan user ci_user -r gitlab -p
    # Build
    - python .ci/build.py -s build_type=$BUILD_TYPE
    # Install
      # Python print() on Windows returns CRLF and will cause issues in CI - use "print('string', end='')" when outputting from python.
    - export PKG_INSTALL_NAME=`python -c "import conanfile; print(conanfile.Properties().conan_recipe, end='')"`
    - conan install $PKG_INSTALL_NAME -g deploy --build=missing --install-folder="./packages"
    # Package
    - export PKG_NAME=`conan inspect . --raw name`
    - export PKG_VERSION=`conan inspect . --raw version`
    - export PKG_ARCH=`uname -m`
    - export PKG_FILENAME="${CI_PROJECT_DIR}\\${PKG_NAME}-${PKG_VERSION}.win10.${PKG_ARCH}.zip"
    - |+
      for PKG_DIR in ./packages/*/; do
        PKG_DIR_NAME=`basename $PKG_DIR`
        for PKG_SUBDIR in ./packages/$PKG_DIR_NAME/*/; do
          PKG_SUBDIR_NAME=`basename $PKG_SUBDIR`
          PKG_FILE_DEST="./package/${PKG_NAME}/${PKG_SUBDIR_NAME}"
          [ -d $PKG_FILE_DEST ] || mkdir -p $PKG_FILE_DEST
          if [ $PKG_SUBDIR_NAME != 'licenses' ]; then
            cp -r $PKG_SUBDIR/* $PKG_FILE_DEST
          else
            for PKG_LICENSE in $PKG_SUBDIR/*; do
              cp $PKG_LICENSE $PKG_FILE_DEST/LICENSE-$PKG_DIR_NAME
            done
          fi
        done
      done
    - cd ./package
    - zip -r $PKG_FILENAME ./

conan-windows-debug:
  variables:
    BUILD_TYPE: Debug
  <<: *conan-windows

conan-windows-release:
  variables:
    BUILD_TYPE: Release
  <<: *conan-windows

conan-windows-32:
  stage: deploy
  tags: [ddisasm-windows]
  needs: []
  variables:
    ARCHITECTURE: x64
  script:
    - systeminfo
    - export PATH="C:\\Program Files\\Python38;$PATH"
    - export PYTHONPATH="$(cygpath -w $(pwd))"
    # Install conan
    - python -m pip install --upgrade conan
    # Setup Remote and Authenticate
    - conan remote add gitlab ${CI_API_V4_URL}/packages/conan
    - conan user ci_user -r gitlab -p
    # The boost options disable building boost with libiconv.  This is important, because we can't get the package to build with --build=libiconv.
    - CI_PROJECT_DIR=$(cygpath -w $(pwd)) python .ci/build.py -s arch=x86 -s compiler.runtime=MT --build=protobuf -o protobuf:with_zlib=False --build=gtirb --build=boost -o boost:zlib=False -o boost:bzip2=False -o boost:without_locale=True -o boost:without_log=True --build=missing

python-wheel:
  stage: build-installers
  needs: [build-ubuntu20-gcc]
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - gtirb-*-py*-none-any.whl
  script:
    - cmake build build
    - make -C build python-wheel
    - cp build/python/dist/*.whl ./

external-pypi:
  stage: deploy
  needs: [build-ubuntu20-gcc, python-wheel]
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*/'
  script:
    - pip3 install gtirb-*-py*-none-any.whl
    - GTIRB_VERSION=$(python3 -c "import gtirb; print(gtirb.__version__)")
    # We won't be releasing our dev packages externally, so fail if this is a
    # .dev package.
    - if [[ "$GTIRB_VERSION" =~ \.dev[[:digit:]]*(\+.*)?$ ]]; then exit 1; fi
    - pip3 install twine wheel setuptools --upgrade;
    - cd build/python;
    - rm -rf build dist gtirb.egg-info;
    - python3 setup.py sdist bdist_wheel;
    - twine check dist/*;
    - twine upload dist/* -u __token__ -p $PYPI_API_KEY;

# On master, we only upload and overwrite `.dev` versions of the python
# package.  Non-.dev versions should only be uploaded on versioned
# release-.* branches.  This is so the versioning of our python packages
# coincides with that of our conan packages, where dev packages are
# produced from master, and stable, versioned packages are produced
# on release-.* branches.
internal-pypi:
  stage: deploy
  needs: [build-ubuntu20-gcc, python-wheel]
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*/'
    # If you need to publish a package for a specific branch, change the
    # package version to something like, '0.0.0.dev0+mybranchname', uncomment
    # the rule below and replace 'mybranchname' with your branch name.
    #- if: '$CI_COMMIT_BRANCH == "mybranchname"'
    #  changes:
    #    - python/gtirb/setup.py.in
  script:
    - pip3 install twine wheel setuptools --upgrade
    - wget https://git.grammatech.com/research/templates/python-module/raw/master/.pypirc
    - sed "s/password = <access token>/password = $GL_PKG_API_TOKEN/" .pypirc > ~/.pypirc
    - pip3 install gtirb-*-py*-none-any.whl
    - NEW_VERSION=$(python3 -c "import gtirb; print(gtirb.__version__)")
    - if [[ "$NEW_VERSION" =~ \.dev[[:digit:]]*(\+.*)?$ && "$CI_COMMIT_REF_NAME" =~ ^release-.* ]]; then exit 1; fi
    - if [[ "$CI_COMMIT_BRANCH" == "master" ]]; then
        if [[ ! "$NEW_VERSION" =~ \.dev[[:digit:]]*$ ]]; then
          echo "[ERROR] Only .dev versions can be uploaded from the master branch.";
          exit 1;
        fi;
        if pip3 install --extra-index-url=$EXTRA_INDEX_URL "gtirb>$NEW_VERSION" 2>/dev/null; then
          echo "[ERROR] The package version being published on master should always be >= the version in the repository.";
          exit 1;
        fi;
        wget https://git.grammatech.com/research/templates/python-module/raw/master/delete_remote_packages.py;
        python3 delete_remote_packages.py $GL_PKG_API_TOKEN gtirb-*-py*-none-any.whl;
      fi
    - cd build/python
    - rm -rf build dist *.egg-info
    - python3 setup.py sdist bdist_wheel
    - twine check dist/*
    - twine upload --verbose --repository repypi dist/*

# Apt packaging related jobs
build-ubuntu20-packages:
  stage: build-installers
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  needs: [build-ubuntu20-gcc]
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - build
  script:
    - pip3 install setuptools wheel --upgrade
    - cd build
    - CPACK_GTIRB_STABLE_PKG_NAME=OFF
    - '[[ ! $CI_COMMIT_REF_NAME =~ ^release-.* ]] || CPACK_GTIRB_STABLE_PKG_NAME=ON'
    - cpack -G "DEB" -D CPACK_GTIRB_STABLE_PKG_NAME=$CPACK_GTIRB_STABLE_PKG_NAME -D CPACK_GTIRB_PACKAGE=debian-lib;
    - cpack -G "DEB" -D CPACK_GTIRB_STABLE_PKG_NAME=$CPACK_GTIRB_STABLE_PKG_NAME -D CPACK_GTIRB_PACKAGE=debian-dev;
    - cpack -G "DEB" -D CPACK_GTIRB_STABLE_PKG_NAME=$CPACK_GTIRB_STABLE_PKG_NAME -D CPACK_GTIRB_PACKAGE=debian-debug;

.setup-test-apt-repo: &setup-test-apt-repo
  stage: test-setup
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - apt-repo
  script:
    - mkdir apt-repo
    - cp build/*.deb apt-repo
    - cd apt-repo && dpkg-scanpackages . /dev/null > Packages


.test-ubuntu-libgtirb-dev: &test-ubuntu-libgtirb-dev
  stage: test-packages1
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - test-install
  script:
    - echo -e "\ndeb [trusted=yes] file:$(pwd)/apt-repo ./\n" >> /etc/apt/sources.list
    - cat /etc/apt/sources.list
    - 'TEST_PKG_NAME=$(dpkg --info apt-repo/libgtirb-dev.deb | sed -n "s/Package: //p")'
    - apt-get update -y && apt-get install -y --allow-unauthenticated $TEST_PKG_NAME
    - cp .ci/test-install.cpp ./
    - g++ test-install.cpp -std=c++17 -o test-install -lgtirb -lstdc++
    - ./test-install

.test-ubuntu-libgtirb: &test-ubuntu-libgtirb
  stage: test-packages2
  script:
    - echo -e "\ndeb [trusted=yes] file:$(pwd)/apt-repo ./\n" >> /etc/apt/sources.list
    - 'TEST_PKG_NAME=$(dpkg --info apt-repo/libgtirb.deb | sed -n "s/Package: //p")'
    - apt-get update -y && apt-get install -y --allow-unauthenticated $TEST_PKG_NAME
    - ./test-install

.test-ubuntu-libgtirb-dbg: &test-ubuntu-libgtirb-dbg
  stage: test-packages1
  script:
    - echo -e "\ndeb [trusted=yes] file:$(pwd)/apt-repo ./\n" >> /etc/apt/sources.list
    - 'TEST_PKG_NAME=$(dpkg --info apt-repo/libgtirb-dbg.deb | sed -n "s/Package: //p")'
    - apt-get update -y && apt-get install -y --allow-unauthenticated $TEST_PKG_NAME
    - '[ -f /usr/lib/debug/.build-id/$(readelf -n /usr/lib/libgtirb.so | grep ''Build ID: '' | cut -d":" -f2 | sed -E ''s/ ([a-f0-9]{2,})([a-f0-9]{30,})/\1\/\2/g'').debug ];'

setup-ubuntu20-test-apt-repo:
   image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
   needs: [build-ubuntu20-packages]
   <<: *setup-test-apt-repo

test-ubuntu20-libgtirb-dev:
   image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
   needs: [setup-ubuntu20-test-apt-repo]
   <<: *test-ubuntu-libgtirb-dev

test-ubuntu20-libgtirb-dbg:
   image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
   needs: [setup-ubuntu20-test-apt-repo]
   <<: *test-ubuntu-libgtirb-dbg

test-ubuntu20-libgtirb:
   image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
   needs: [setup-ubuntu20-test-apt-repo,test-ubuntu20-libgtirb-dev]
   <<: *test-ubuntu-libgtirb

debian-installer-ubuntu20:
  stage: deploy
  image: $DOCKER_REGISTRY/rewriting/gtirb/ubuntu20
  needs: [test-ubuntu20-libgtirb, build-ubuntu20-packages]
  artifacts:
    name: "$CI_COMMIT_REF_NAME-$CI_JOB_NAME"
    paths:
      - '*gtirb*.deb'
  script:
    - cp build/*gtirb*.deb ./

.apt-upload: &apt-upload
  stage: deploy-apt
  trigger:
    project: rewriting/utility/package-uploader
    strategy: depend

apt-public-unstable:
  <<: *apt-upload
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    JOB_NAME: debian-installer-ubuntu20
    APT_REPO: public
    APT_REPO_CODENAMES: focal
    APT_REPO_COMPONENT: unstable

apt-public-stable:
  <<: *apt-upload
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*/'
  variables:
    JOB_NAME: debian-installer-ubuntu20
    APT_REPO: public
    APT_REPO_CODENAMES: focal
    APT_REPO_COMPONENT: stable

apt-internal-unstable:
  <<: *apt-upload
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'
  variables:
    JOB_NAME: debian-installer-ubuntu20
    APT_REPO: internal
    APT_REPO_CODENAMES: focal
    APT_REPO_COMPONENT: unstable

apt-internal-stable:
  <<: *apt-upload
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*/'
  variables:
    JOB_NAME: debian-installer-ubuntu20
    APT_REPO: internal
    APT_REPO_CODENAMES: focal
    APT_REPO_COMPONENT: stable

maven-central-upload:
  stage: deploy
  needs: [build-ubuntu20-gcc]
  trigger:
    project: rewriting/utility/package-uploader
    strategy: depend
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*/'
  variables:
    JOB_NAME: build-ubuntu20-gcc
    JAVA_POM_SUBDIR: ./build/java

.windows-upload: &windows-upload
  stage: upload
  trigger:
    project: rewriting/utility/package-uploader
    strategy: depend
  needs: [conan-windows-release]

windows-upload-public:
  <<: *windows-upload
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*/'
    - if: '$CI_COMMIT_REF_NAME == "master"'
  variables:
    JOB_NAME: conan-windows-release
    FILESERVER: public
    FILESERVER_SUBDIR_NAME: windows-release

windows-upload-internal:
  <<: *windows-upload
  rules:
    - if: '$CI_COMMIT_REF_NAME =~ /^release-.*/'
    - if: '$CI_COMMIT_REF_NAME == "master"'
  variables:
    JOB_NAME: conan-windows-release
    FILESERVER: internal
    FILESERVER_SUBDIR_NAME: windows-release

wheel-upload-public:
  stage: upload
  trigger:
    project: rewriting/utility/package-uploader
    strategy: depend
  needs: [python-wheel]
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
  variables:
    JOB_NAME: python-wheel
    FILESERVER: public
    FILESERVER_SUBDIR_NAME: python
