variables:
  DOCKER_REGISTRY: "docker.grammatech.com:14850"
  LOCAL_IMAGE_NAME: '$CI_BUILD_REF_NAME-$CI_PIPELINE_ID'
  GIT_SUBMODULE_STRATEGY: recursive

before_script:
  - docker info
  - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY

stages:
  - build-test-deploy-cleanup-ubuntu16-gcc
  - build-test-deploy-cleanup-ubuntu16-clang
# - build-test-deploy-cleanup-ubuntu14-gcc
  - build-test-deploy-cleanup-arch-gcc
  - deploy-and-cleanup

.build-template: &build
  script:
    - docker build -f .ci/Dockerfile.$OS -t ${LOCAL_IMAGE_NAME}-${OS}-${COMPILER} .
    - docker run ${LOCAL_IMAGE_NAME}-${OS} TestGTIRB
    - docker tag ${LOCAL_IMAGE_NAME}-${OS} $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS}-${COMPILER};
    - docker push $DOCKER_REGISTRY/$CI_PROJECT_PATH/${OS}-${COMPILER};
    - docker rmi -f ${LOCAL_IMAGE_NAME}-${OS}-${COMPILER}

build-ubuntu16-gcc:
  stage: build-test-deploy-cleanup-ubuntu16-gcc
  variables:
    OS: 'ubuntu16'
    COMPILER: 'gcc'
  <<: *build

build-ubuntu16-clang:
  stage: build-test-deploy-cleanup-ubuntu16-clang
  variables:
    OS: 'ubuntu16'
    COMPILER: 'clang'
  <<: *build

# build-ubuntu14:
#   stage: build-test-deploy-cleanup-ubuntu14-gcc
#   variables:
#     OS: 'ubuntu14'
#   <<: *build

build-arch:
  stage: build-test-deploy-cleanup-arch-gcc
  variables:
    OS: 'arch'
    COMPILER: 'gcc'
  <<: *build

pages:
  stage: deploy-and-cleanup
  script:
    - docker run ${LOCAL_IMAGE_NAME}-${OS}-${COMPILER} /bin/bash -c "mkdir -p /public && cp -R doc/html/* /public/"
    - docker cp $(docker ps -alq):/public ./
    - docker rmi -f ${LOCAL_IMAGE_NAME}-${OS}-${COMPILER}
  artifacts:
    paths:
      - public
  only:
    - master

cleanup:
  stage: deploy-and-cleanup
  script:
    - docker rmi -f ${LOCAL_IMAGE_NAME}-${OS}-${COMPILER}
  except:
    - master
