from typing import MutableMapping, Iterator, Tuple, TypeVar

K = TypeVar("K")
V = TypeVar("V")

class SortedDict(MutableMapping[K, V]):
    def __delitem__(self, key: K) -> None: ...
    def __getitem__(self, key: K) -> V: ...
    def __iter__(self) -> Iterator[K]: ...
    def __len__(self) -> int: ...
    def __setitem__(self, key: K, value: V) -> None: ...
    def irange(
        self,
        minimum: K | None = ...,
        maximum: K | None = ...,
        inclusive: Tuple[bool, bool] = ...,
        reverse: bool = ...,
    ) -> Iterator[K]: ...
